name = "embedded_components"
description = "Platform agnostic drivers to interface external components"
long-description = '''# embedded-components

Platform agnostic drivers to interface external components.

This crate is a snapshot of the `components` of [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/tree/master/components).

Any bug report, issue, contribution must be adressed to the [Ada Drivers
Library](https://github.com/AdaCore/Ada_Drivers_Library/) repo.

'''
version = "0.2.0-dev"
licenses = "BSD-3-Clause"

authors = ["AdaCore"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>", "Jeremy Grosser <jeremy@synack.me>"]
maintainers-logins = ["Fabien-Chouteau", "JeremyGrosser"]
website = "https://github.com/AdaCore/Ada_Drivers_Library/"
tags = ["embedded", "nostd"]

[[depends-on]]
adl_middleware = "~0.1.1"
